Banca.Application/Controllers/EstadoCuentaController.cs
using Banca.Application.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace Banca.Application.Controllers
{
    public class EstadoCuentaController : Controller
    {

        private readonly HttpClient _httpClient;
        private readonly string _apiBaseUrl;

        public EstadoCuentaController(HttpClient httpClient, IConfiguration configuration)
        {
            _httpClient = httpClient;
            _apiBaseUrl = configuration["UrlSettings:ApiBaseUrl"]; 
        }
        // GET: EstadoCuentaController
        public async Task<IActionResult> Index(int id)
        {
            var response = await _httpClient.GetAsync($"{_apiBaseUrl}api/TitularTarjeta/{id}");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var estadoDeCuenta = JsonSerializer.Deserialize<EstadoDeCuentaViewModel>(content);
                return View(estadoDeCuenta);
            }
            return NotFound();
        }

        public async Task<ActionResult> ExportarPDF(int titularTarjetaId)
        {

            var response = await _httpClient.GetAsync($"{_apiBaseUrl}api/TitularTarjeta/{titularTarjetaId}");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var estadoDeCuenta = JsonSerializer.Deserialize<EstadoDeCuentaViewModel>(content);

                var pdfResponse = await _httpClient.PostAsJsonAsync($"{_apiBaseUrl}api/TitularTarjeta/ExportarEstadoPDF", estadoDeCuenta);

                if (pdfResponse.IsSuccessStatusCode)
                {
                    var pdfData = await pdfResponse.Content.ReadAsByteArrayAsync();
                    return File(pdfData, "application/pdf", "EstadoDeCuenta.pdf");
                }
            }
            return NotFound();

        }
    }
}

Banca.Application/Controllers/HomeController.cs
using Banca.Application.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Net.Http;
using System.Text.Json;

namespace Banca.Application.Controllers
{
	public class HomeController : Controller
	{
        private readonly HttpClient _httpClient;
        private readonly string _apiBaseUrl;

        public HomeController(HttpClient httpClient, IConfiguration configuration)
        {
            _httpClient = httpClient;
            _apiBaseUrl = configuration["UrlSettings:ApiBaseUrl"]; 
        }
        public async Task<IActionResult> Index()
		{
            var response = await _httpClient.GetAsync($"{_apiBaseUrl}api/TitularTarjeta");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var titularesTarjeta = JsonSerializer.Deserialize<List<TitularTarjetaViewModel>>(content);
                return View(titularesTarjeta);
            }

            return NotFound();
        }

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Banca.Application/Views/Home/Index.cshtml
@using Banca.Application.Utils
@model IEnumerable<Banca.Application.Models.TitularTarjetaViewModel>;
@{
    ViewData["Title"] = "Banca Digital";
}


@foreach (var item in Model)
{
    <a asp-controller="EstadoCuenta" asp-action="Index" asp-route-id="@item.TitularTarjetaId" class="card credit-card-button text-decoration-none">
        <div class="card-body">
            <h5 class="card-title">@item.NombreTitular</h5>
            <p class="card-text">
                <span class="card-number">@item.NumeroTarjeta.ToCardFormat()</span>
                <span class="card-icon"></span>
            </p>
            <p class="card-text">Saldo Actual: @item.SaldoActual.ToString("C")</p>
            <p class="card-text">Límite de Crédito: @item.LimiteCredito.ToString("C")</p>
            <p class="card-text"><small class="text-muted">Ver estado</small></p>
        </div>
    </a>
}


@section Scripts {
    <script>
        $(document).ready(function () {
            $('.card-number').each(function () {
                var cardNumber = $(this).text().trim();
                var cardIconSpan = $(this).next('.card-icon');

                if (cardNumber.startsWith('4')) {
                    cardIconSpan.html('<i class="bi bi-credit-card-2-front-fill"></i>');
                } else if (cardNumber.startsWith('5')) {
                    cardIconSpan.html('<i class="bi bi-credit-card-fill"></i>');
                }
            });
        });
    </script>
}