Banca.Application/Controllers/CompraController.cs
using Banca.Application.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;

namespace Banca.Application.Controllers
{
    public class CompraController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly string _apiBaseUrl;
        public CompraController(HttpClient httpClient, IConfiguration configuration)
        {
            _httpClient = httpClient;
            _apiBaseUrl = configuration["UrlSettings:ApiBaseUrl"];
        }
        public IActionResult Crear(int id)
        {
            ViewBag.TitularId = id;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Crear (CompraViewModel compra)
        {

            var response = await _httpClient.PostAsJsonAsync($"{_apiBaseUrl}api/Compra/", compra);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index","EstadoCuenta", new { id = compra.TitularTarjetaId }); 
            }

            ModelState.AddModelError(string.Empty, "Ocurrió un error al crear la compra");
            return View(compra);

        }
    }
}

Banca.Application/Controllers/EstadoCuentaController.cs
using Banca.Application.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace Banca.Application.Controllers
{
    public class EstadoCuentaController : Controller
    {

        private readonly HttpClient _httpClient;
        private readonly string _apiBaseUrl;

        public EstadoCuentaController(HttpClient httpClient, IConfiguration configuration)
        {
            _httpClient = httpClient;
            _apiBaseUrl = configuration["UrlSettings:ApiBaseUrl"]; 
        }
        // GET: EstadoCuentaController
        public async Task<IActionResult> Index(int id)
        {
            var response = await _httpClient.GetAsync($"{_apiBaseUrl}api/TitularTarjeta/{id}");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var estadoDeCuenta = JsonSerializer.Deserialize<EstadoDeCuentaViewModel>(content);
                return View(estadoDeCuenta);
            }
            return NotFound();
        }

        public async Task<ActionResult> ExportarPDF(int titularTarjetaId)
        {

            var response = await _httpClient.GetAsync($"{_apiBaseUrl}api/TitularTarjeta/{titularTarjetaId}");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var estadoDeCuenta = JsonSerializer.Deserialize<EstadoDeCuentaViewModel>(content);

                var pdfResponse = await _httpClient.PostAsJsonAsync($"{_apiBaseUrl}api/TitularTarjeta/ExportarEstadoPDF", estadoDeCuenta);

                if (pdfResponse.IsSuccessStatusCode)
                {
                    var pdfData = await pdfResponse.Content.ReadAsByteArrayAsync();
                    return File(pdfData, "application/pdf", "EstadoDeCuenta.pdf");
                }
            }
            return NotFound();

        }
    }
}

Banca.Application/Controllers/PagoController.cs
using Banca.Application.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;

namespace Banca.Application.Controllers
{
    public class PagoController : Controller
    {

        private readonly HttpClient _httpClient;
        private readonly string _apiBaseUrl;
        public PagoController(HttpClient httpClient, IConfiguration configuration)
        {
            _httpClient = httpClient;
            _apiBaseUrl = configuration["UrlSettings:ApiBaseUrl"];
        }
        public IActionResult Crear(int id)
        {
            ViewBag.TitularId = id;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Crear(PagoViewModel pago)
        {

            var response = await _httpClient.PostAsJsonAsync($"{_apiBaseUrl}api/Pago/", pago);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "EstadoCuenta", new { id = pago.TitularTarjetaId });
            }

            ModelState.AddModelError(string.Empty, "Ocurrió un error al crear el pago");
            return View(pago);

        }
    }
}

Banca.Application/Views/EstadoCuenta/Index.cshtml
@using Banca.Application.Utils
@model EstadoDeCuentaViewModel

@{
    ViewBag.Title = "Estado de Cuenta";
}

<h1 class="text-center mb-4">Estado de Cuenta</h1>
<div class="d-flex justify-content-between mb-3">
    <a href="@Url.Action("Index", "Home")" class="btn btn-outline-primary">Regresar</a>

    <form asp-action="ExportarPDF" asp-controller="EstadoCuenta">
        <input asp-for="TitularTarjetaId" hidden />
        <button class="btn btn-outline-danger" type="submit">Descargar PDF</button>
    </form>
</div>
<div class="container">
    <!-- Información del Titular y Detalles Financieros -->
    <div class="row my-4">
        <div class="col-lg-6">
            <div class="card shadow-sm p-3 mb-2 bg-white rounded">
                <div class="card-body">
                    <h2 class="card-title">Información del Titular</h2>
                    <p><strong>Titular:</strong> @Model.NombreTitular</p>
                    <p><strong>Número de Tarjeta:</strong> @Model.NumeroTarjeta.ToCardFormat()</p>
                    <p></p>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card shadow-sm p-3 mb-2 bg-white rounded">
                <div class="card-body">
                    <h2 class="card-title">Detalles Financieros</h2>
                    <p><strong>Saldo Actual:</strong> @Model.SaldoActual.ToString("C")</p>
                    <p><strong>Límite de Crédito:</strong> @Model.LimiteCredito.ToString("C")</p>
                    <p><strong>Saldo Disponible:</strong> @Model.SaldoDisponible.ToString("C")</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Compras del Mes -->
    <div class="row">
        <div class="col-12">
            <div class="card shadow-sm p-3 mb-5 bg-white rounded">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center pb-4">
                        <h2 class="card-title mb-0">Compras del Mes</h2>
                        <a asp-controller="Compra" asp-action="Crear" asp-route-id="@Model.TitularTarjetaId" class="btn btn-outline-success">Nueva Compra</a>
                    </div>
                    <table id="comprasTable" class="table table-striped mt-3">
                        <thead>
                            <tr>
                                <th>Fecha</th>
                                <th>Descripción</th>
                                <th>Monto</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var compra in Model.ComprasDelMes)
                            {
                                <tr>
                                    <td>@compra.Fecha.ToShortDateString()</td>
                                    <td>@compra.Descripcion</td>
                                    <td>@compra.Monto.ToString("C")</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Pagos -->
    <div class="row">
        <div class="col-12">
            <div class="card shadow-sm p-3 mb-5 bg-white rounded">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center pb-4">
                        <h2 class="card-title mb-0">Pagos</h2>
                        <a asp-controller="Pago" asp-action="Crear" asp-route-id="@Model.TitularTarjetaId" class="btn btn-outline-success">Realizar Pago</a>
                    </div>
                    <table id="pagosTable" class="table table-striped mt-3">
                        <thead>
                            <tr>
                                <th>Fecha</th>
                                <th>Monto</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var pago in Model.Pagos)
                            {
                                <tr>
                                    <td>@pago.FechaPago.ToShortDateString()</td>
                                    <td>@pago.Monto.ToString("C")</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


    <!-- Resumen Financiero -->
    <div class="row">
        <div class="col-12">
            <div class="card shadow-sm p-3 mb-5 bg-white rounded">
                <div class="card-body">
                    <h2 class="card-title">Resumen Financiero</h2>
                    <p><strong>Monto Total Compras Mes Actual:</strong> @Model.MontoTotalComprasMesActual.ToString("C")</p>
                    <p><strong>Monto Total Compras Mes Anterior:</strong> @Model.MontoTotalComprasMesAnterior.ToString("C")</p>
                    <p><strong>Interés Bonificable:</strong> @Model.InteresBonificable.ToString("C")</p>
                    <p><strong>Cuota Mínima a Pagar:</strong> @Model.CuotaMinimaAPagar.ToString("C")</p>
                    <p><strong>Monto Total a Pagar:</strong> @Model.MontoTotalAPagar.ToString("C")</p>
                    <p><strong>Pago de Contado con Intereses:</strong> @Model.PagoContadoConIntereses.ToString("C")</p>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    
    @* <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> *@
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>



    <script>
        $(document).ready(function () {
        $("#comprasTable").DataTable({
            dom: 'Bfrtip',
            buttons: [
                {
                        extend: 'excelHtml5',
                        text: 'Exportar a Excel',
                        filename: 'DetalleDeCompras'
                }
            ],
            language: {
                search: "Buscar",
                lengthMenu: "Mostrar _MENU_ registros",
                zeroRecords: "No se encontraron registros",
                emptyTable: "Ningún dato disponible en esta tabla",
                info: "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                infoEmpty: "Mostrando registros del 0 al 0 de un total de 0 registros",
                infoFiltered: "(filtrado de un total de _MAX_ registros)",
                loadingRecords: "Cargando",
                paginate: {
                    first: "Primero",
                    last: "Ultimo",
                    next: "siguiente",
                    previous: "Anterior"
                },
                aria: {
                    sortAscending: ": Activar para ordenar la columna de manera ascendente",
                    sortDescending: ": Activar para ordenar la columna de manera descendente"
                },
                buttons: {
                    excel: 'Exportar a Excel'
                }
            },
            columnDefs: [{
                targets: 2,
                orderable: false,
                searchable: false
            }]

        });

        $("#pagosTable").DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'excelHtml5',
                        text: 'Exportar a Excel',
                        filename: 'DetalleDePagos'
                    }
                ],
            language: {
                search: "Buscar",
                lengthMenu: "Mostrar _MENU_ registros",
                zeroRecords: "No se encontraron registros",
                emptyTable: "Ningún dato disponible en esta tabla",
                info: "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                infoEmpty: "Mostrando registros del 0 al 0 de un total de 0 registros",
                infoFiltered: "(filtrado de un total de _MAX_ registros)",
                loadingRecords: "Cargando",
                paginate: {
                    first: "Primero",
                    last: "Ultimo",
                    next: "siguiente",
                    previous: "Anterior"
                },
                aria: {
                    sortAscending: ": Activar para ordenar la columna de manera ascendente",
                    sortDescending: ": Activar para ordenar la columna de manera descendente"
                },
                    buttons: {
                        excel: 'Exportar a Excel'
                    }

            },
            columnDefs: [{
                // targets: 2,
                orderable: false,
                searchable: false
            }]
        });
        });
    </script>
}